### ISSUE TITLE
to heck is this

### ISSUE THREAD

**Issue by MDFL64** [glua/lua-quiz#1]
is it a maymay?

**Comment by SwadicalRag** [comment]
the idea was that we write questions about lua
put them in a giant file
write a quiz web page
and make people take the quiz

their quiz score gives them extra bragging rights

👌 🙆

**Comment by gspetrou** [comment]
It's just smells

**Comment by SwadicalRag** [comment]
mean

**Comment by MDFL64** [comment]
cool

so how many of the questions can be based on my strong opinions?

**Comment by SwadicalRag** [comment]
idk up to u XD

**Comment by SwadicalRag** [comment]
new questions go in `questions.js` kthxbai
